services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: regis-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app        # asegura c√≥digo en caliente
      - ./data:/app/data              # acceso a carpeta local 'data'
    depends_on:
      - postgres
    networks:
      - regis-net

  postgres:
    image: pgvector/pgvector:pg15
    container_name: regis-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: regisdb
    volumes:
      - regis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - regis-net

volumes:
  regis_data:
    external: true
    name: junction_2025_bof-challenge_regis_data

networks:
  regis-net:
    driver: bridge
