version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: regis-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: regis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - regis-network

  fastapi:
    build: ./app
    container_name: regis-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/regis
    volumes:
      - ./app:/app
      - ../data:/data
    networks:
      - regis-network

volumes:
  postgres_data:

networks:
  regis-network:
    driver: bridge
